import { useState } from "react";
import ReactModal from "react-modal";
import { ListaPromociones } from "./components/ListaPromociones";
import { ModalNewPromocion } from "./components/ModalNewPromocion";
import usePromociones from "./usePromociones/usePromociones";
import { ToastContainer } from "react-toastify";

// Generated by https://quicktype.io

export interface Promociones {
  succes: Succe[];
}

export interface Succe {
  id: number;
  activo: number;
  nombre: string;
  porcentaje: number;
  created_at: Date;
  updated_at: Date;
}

export const PromocionesLayout = () => {
  const { data, isLoading } = usePromociones();
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const listPromociones: Promociones = data?.data;
  return (
    <>
      <button
        className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700"
        onClick={() => setModalIsOpen(true)}
      >
        Crear Nueva Promocion
      </button>
      {isLoading ? (
        <p>Cargando informacion de promociones...</p>
      ) : (
        <ListaPromociones promocion={listPromociones.succes} />
      )}
      <ReactModal
        isOpen={modalIsOpen}
        onRequestClose={() => setModalIsOpen(false)}
        className="fixed inset-0 flex items-center justify-center p-4"
        overlayClassName="fixed inset-0 bg-black bg-opacity-50"
      >
        <div className="bg-white rounded-lg p-6 max-w-lg w-full">
          <ModalNewPromocion />
          <button
            className="mt-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-700"
            onClick={() => setModalIsOpen(false)}
          >
            Cerrar
          </button>
        </div>
      </ReactModal>
      <ToastContainer/>
    </>
  );
};
