import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast, ToastContainer } from "react-toastify";
import { clienteAxios } from "../../config/axios";
// Generated by https://quicktype.io

export interface Auth {
  succes: string;
}
// Generated by https://quicktype.io

export interface Error {
  message: string;
  errors:  Errors;
}

export interface Errors {
  email: string[];
}

import loadingSpiner from './assets/loading.svg'
import { isAxiosError } from "axios";
export const LoginLayout = () => {
    const [email, setEmail] = useState('');
    const navigate = useNavigate()
  const [password, setPassword] = useState('');
  const [loading,setloading] = useState(false)
  const handleLogin = async(e: React.FormEvent) => {
    e.preventDefault();
    // Aquí puedes manejar el login
    setloading(true)
    try {
        const datos ={
          email:email,
          password:password
        }
      const {data} = await clienteAxios.post('/api/user/auth',datos) 
      const resp:Auth = data;
      if(data?.error)
      {
        toast.error(data?.error)
      }
      if(resp?.succes)  
      {  
        localStorage.setItem('token',resp?.succes)
        navigate('/panel')
      }
    } catch (error) {
      if(isAxiosError(error)){
        const errorback:Error = error.response?.data
        toast.error(errorback.message)
      }
    }
    setloading(false)
    // navigate('/panel')
  };
  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-blue-300 to-blue-600">
      <div className="bg-white p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 className="text-2xl font-bold text-blue-800 mb-6 text-center">Centro Médico - Iniciar Sesión</h2>
        <form onSubmit={handleLogin}>
          <div className="mb-4">
            <label className="block text-blue-800 font-semibold mb-2" htmlFor="email">
              Correo Electrónico
            </label>
            <input
              type="email"
              id="email"
              className="w-full p-3 border border-blue-300 rounded focus:outline-none focus:border-blue-500"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
            />
          </div>
          <div className="mb-6">
            <label className="block text-blue-800 font-semibold mb-2" htmlFor="password">
              Contraseña
            </label>
            <input
              type="password"
              id="password"
              className="w-full p-3 border border-blue-300 rounded focus:outline-none focus:border-blue-500"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </div>
          {loading ? 
            <button
            type="button"
            className="w-full bg-blue-600 text-white py-3 rounded hover:bg-blue-700 transition-colors flex justify-center items-center"
          >
            <img src={loadingSpiner} alt="" className="w-8 h-8" />

          </button>
          :
          
            <button
              type="submit"
              className="w-full bg-blue-600 text-white py-3 rounded hover:bg-blue-700 transition-colors"
            >
              Iniciar Sesión
            </button>
          
          }
        </form>
        <div className="mt-6 text-center">
          <a href="#" className="text-blue-700 hover:text-blue-900 text-sm">
            ¿Olvidaste tu contraseña?
          </a>
        </div>
      </div>
      <ToastContainer/>
    </div>
  )
}
