// Generated by https://quicktype.io

export interface Motivos {
    succes: Succe[];
}

export interface Succe {
    id:         number;
    nombre:     string;
    created_at: Date;
    updated_at: Date;
}
