import { useState } from "react";
import ReactModal from "react-modal";
import { ModalNewProduct } from "./components/ModalNewProduct";
import useProductos from "./hooks/useProductos";
// import { ListProducts } from "../components/ListProducts";
import spiner from './assets/spiner.svg'
import ListProductos from "./components/ListProductos";


// Generated by https://quicktype.io

export interface Productos {
  succes: Succe[];
}

export interface Succe {
  id:               number;
  nombre:           string;
  id_marca:         number;
  nombre_marca:     string;
  id_promocion:     number;
  nombre_promocion: string;
  precio:           number;
  estado:           string;
  porcentaje:       number;
  imagen1:          string;
  imagen2:          string;
  imagen3:          string;
  imagen4:          string;
}

export const ProductosLayout = () => {
  const {data,isLoading} = useProductos()
  const [modalIsOpen, setModalIsOpen] = useState(false);
  const productos:Productos = data?.data; 

  return (
    <>
      <button
        className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700"
        onClick={() => setModalIsOpen(true)}
      >
        Crear Nuevo Producto
      </button>
        <ListProductos succes={productos?.succes} />
      <ReactModal
        isOpen={modalIsOpen}
        onRequestClose={() => setModalIsOpen(false)}
        className="fixed inset-0 flex items-center justify-center  overflow-hidden"
        overlayClassName="fixed inset-0 bg-black bg-opacity-50"
      >
        <div className="bg-white rounded-lg p-2 max-w-lg w-full h-full overflow-auto ">
          <ModalNewProduct />
          <button
            className="mt-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-700"
            onClick={() => setModalIsOpen(false)}
          >
            Cerrar
          </button>
        </div>
      </ReactModal>

      {/* spiner */}
      <ReactModal
        isOpen={isLoading}
        onRequestClose={() => setModalIsOpen(false)}
        className="fixed inset-0 flex items-center justify-center "
        overlayClassName="fixed inset-0 bg-black bg-opacity-50"
      >
         <img src={spiner} alt="" className="w-10 h-10"/>
      </ReactModal>
    </>
  );
};
