import React, { useState } from "react";
import ReactModal from "react-modal";
import ListCaracteristicas from "./components/ListCaracteristicas";
import { Input } from "../../../componentsGlobal/Input";
import { clienteAxios } from "../../../config/axios";
import { toast } from "react-toastify";
import useSWR from "swr";



// Generated by https://quicktype.io

export interface Caracteristicas {
    succes: Succe[];
}

export interface Succe {
    id:         number;
    nombre:     string;
    created_at: Date;
    updated_at: Date;
}

const Caracteristicas = () => {
    const token = localStorage.getItem('token')
  const [modalIsOpen, setModalIsOpen] = useState<boolean>(false);
  const [loadingDelete] = useState<boolean>(false);
  const [nombre,setnombre] = useState<number|string>('');

  const createMarac = async(e:React.FormEvent) =>
  {
    e.preventDefault();

    try {
        if(nombre!== '')
        {
            const datos = {
                nombre:nombre
            }
            toast.success('Guardando datos...')
            const {data} = await clienteAxios.post('/api/caracteristica/create',datos,{
                headers:{
                    Authorization:`Bearer ${token}`
                }
            })
            console.log(data)
            toast.success('Se creo de forma correcta ');
            mutate()
        }else{
            toast.warning('Nombre de la caracteristica es obligatorio')
        }
    } catch (error) {
        console.log(error)
        toast.error('Se genero un error inesperado');
    }
  }


  const {data,isLoading,mutate} = useSWR('/api/caracteristicas/all',()=>
    clienteAxios.get('/api/caracteristica/all'))

  const caracteristicas:Caracteristicas = data?.data;
  return (
    <>
      <p>
        {isLoading
          ? "Cargando informacion"
          : loadingDelete
          ? "Eliminando marca"
          : null}
      </p>
      <button
        className="mt-4 px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-700"
        onClick={() => setModalIsOpen(true)}
      >
        Crear Nuevo Marca
      </button>
      <ListCaracteristicas succes={caracteristicas} mutate={mutate} />
      <ReactModal
        isOpen={modalIsOpen}
        //   onRequestClose={() => setModalIsOpen(false)}
        className="fixed inset-0 flex items-center justify-center p-4"
        overlayClassName="fixed inset-0 bg-black bg-opacity-50"
      >
        <div className="bg-white rounded-lg p-6 max-w-lg w-full">
          <form onSubmit={createMarac} action="" className="w-full flex flex-col gap-2 p-2">
            <Input type="text" nombre="Nombre de Caracteristica" setValue={setnombre} valueInput={nombre}/>
            <button className="text-white font-bold bg-green-500 p-2 rounded-sm hover:bg-green-800">
                Crear Caracteristica
            </button>
          </form>

          <button
            className="mt-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-700"
              onClick={() => setModalIsOpen(false)}
          >
            Cerrar
          </button>
        </div>
      </ReactModal>
    </>
  );
};

export default Caracteristicas;
